version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: cloud_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./cloud-security-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_URI: postgres://postgres:example@db:5432/cloud_security

  frontend:
    build: ./frontReact
    ports:
      - "3000:80"

volumes:
  pgdata:
