module.exports = [
  {
    id: 'mfa',
    text: 'Utilisez-vous l’authentification multifacteur (MFA) ?',
    riskWeight: 30,
    recommendation: 'Activez la MFA pour renforcer l’accès à vos comptes cloud.',
    owasp: ['Identification and Authentication Failures'],
  },
  {
    id: 'passwordStrong',
    text: 'Vos mots de passe sont-ils forts et uniques ?',
    riskWeight: 20,
    recommendation: 'Utilisez des mots de passe complexes et un gestionnaire de mots de passe.',
    owasp: ['Cryptographic Failures'],
  },
  {
    id: 'publicSharing',
    text: 'Partagez-vous souvent des fichiers cloud via des liens publics ?',
    riskWeight: 25,
    inverse: true,
    recommendation: 'Évitez le partage public, utilisez des permissions spécifiques.',
    owasp: ['Security Misconfiguration'],
  },
  {
    id: 'dataBackup',
    text: 'Effectuez-vous régulièrement des sauvegardes de vos données cloud ?',
    riskWeight: 15,
    recommendation: 'Planifiez des sauvegardes régulières pour prévenir les pertes de données.',
  },
  {
    id: 'accessReview',
    text: 'Revoyez-vous régulièrement les droits d’accès à vos fichiers ?',
    riskWeight: 10,
    recommendation: 'Faites un audit périodique des accès pour limiter les risques.',
  },
  {
    id: 'encryptionUsed',
    text: 'Vos données cloud sont-elles chiffrées au repos et en transit ?',
    riskWeight: 20,
    recommendation: 'Assurez-vous que les données sont chiffrées pour prévenir les interceptions.',
    owasp: ['Cryptographic Failures'],
  },
  {
    id: 'iamPolicies',
    text: 'Utilisez-vous des politiques IAM strictes (basées sur les rôles) ?',
    riskWeight: 15,
    recommendation: 'Utilisez IAM/RBAC pour limiter les privilèges d’accès.',
    owasp: ['Broken Access Control'],
  },
  {
    id: 'cloudAudit',
    text: 'Avez-vous audité la configuration de votre infrastructure cloud ?',
    riskWeight: 10,
    recommendation: 'Effectuez un audit régulier pour identifier les failles de configuration.',
    owasp: ['Security Misconfiguration'],
  },
  {
    id: 'internalThreats',
    text: 'Surveillez-vous les comportements suspects des utilisateurs internes ?',
    riskWeight: 15,
    recommendation: 'Mettez en place des outils de détection d’activités anormales.',
  },
  {
    id: 'apiSecurity',
    text: 'Vos interfaces et APIs sont-elles sécurisées (authentification, limitation) ?',
    riskWeight: 20,
    recommendation: 'Protégez vos APIs avec des clés d’accès, authentification et limites de requêtes.',
    owasp: ['Broken Access Control', 'Security Misconfiguration', 'API Insecurity'],
  },
  {
    id: 'cloudMisuse',
    text: 'Empêchez-vous l’usage inapproprié des services cloud (stockage public, apps perso) ?',
    riskWeight: 10,
    recommendation: 'Sensibilisez à l’usage des services cloud et restreignez les usages non autorisés.',
  },
  {
    id: 'loggingMonitoring',
    text: 'Avez-vous activé la journalisation et la surveillance des événements ?',
    riskWeight: 20,
    recommendation: 'Activez les logs pour suivre les accès, erreurs et activités suspectes.',
    owasp: ['Security Misconfiguration', 'Cryptographic Failures'],
  },
  {
    id: 'cloudVisibility',
    text: 'Avez-vous une visibilité complète sur les services cloud utilisés ?',
    riskWeight: 10,
    recommendation: 'Utilisez des outils de gestion centralisée pour avoir une vue d’ensemble.',
  },
  {
    id: 'weakConsole',
    text: 'L’accès à votre console d’administration cloud est-il protégé (IP, MFA) ?',
    riskWeight: 15,
    recommendation: 'Renforcez la console admin avec restriction IP, MFA et journalisation.',
    owasp: ['Identification and Authentication Failures', 'Security Misconfiguration'],
  },
  {
    id: 'securityArchitecture',
    text: 'Disposez-vous d’une architecture de sécurité cloud bien définie ?',
    riskWeight: 15,
    recommendation: 'Adoptez une architecture sécurité cloud alignée sur les bonnes pratiques OWASP.',
  },
];